- app/lib/ui/components/theme_selector.dart
- app/lib/ui/main_screen.dart
This PR extracts the theme selector dropdown as an autonomous widget.
> Add ThemeSelector widget

- app/lib/ui/components/components_screen.dart
- app/lib/ui/main_screen.dart
add accessibility semantics on the app
> Feature/ts accessibility-app

- app/CHANGELOG.md
- app/lib/l10n/ods_flutter_en.arb
- app/lib/ui/components/components.dart
- app/lib/ui/components/utilities/customization_bottom_sheet.dart
- app/lib/ui/theme/theme_selector.dart
- library/lib/theme/ods_theme.dart
> 169 - Update Customization Bottom Sheet

- app/CHANGELOG.md
- app/lib/ui/components/components_screen.dart
- app/lib/ui/main_screen.dart
- app/lib/ui/utilities/navigation_items.dart
- library/lib/components/app_bar/top/ods_top_app_bars.dart
- library/lib/components/card/ods_small_card.dart
- library/lib/theme/ods_theme.dart
> 178 bug ods component screen navigation rail

- app/CHANGELOG.md
- app/lib/ui/components/components.dart
- app/lib/ui/guidelines/guidelines.dart
- app/test/widget_test.dart
> component list page reordering and changelog

- library/lib/theme/ods_typography.dart
> 210 update the typography tokens for flutter

- NOTICE.txt
- app/CHANGELOG.md
- app/assets/recipes/ic_heart_favorite.svg
- app/lib/ui/components/navigation_bar/navigarion_bar_customization.dart
- app/lib/ui/components/navigation_bar/navigation_bar.dart
> 194 bottom navigation number items update

- app/CHANGELOG.md
- app/lib/ui/components/snackbars/snackbars.dart
> 199 bug snackbar demo trigger update

- library/lib/theme/ods_typography.dart
> updated headline & titles to be in bold

- app/lib/ui/components/sliders/sliders.dart
- library/CHANGELOG.md
- library/lib/components/sliders/ods_slider.dart
> synchronization parameter name ods-android

- docs/_data/data_menus.yml
- docs/components/checkboxes.md
- docs/components/checkboxes_docs.md
- docs/components/navigationBar.md
> add checkbox and navigationBar

- app/CHANGELOG.md
- library/CHANGELOG.md
> add changelog

- library/lib/components/card/ods_horizontal_card.dart
> library: align center title vertical in card

- app/CHANGELOG.md
- app/lib/ui/components/app_bars/top/top_app_bars.dart
> 255 bug ods component top app bars

- app/lib/ui/guidelines/spacings/guideline_spacings_screen.dart
- app/lib/ui/guidelines/spacings/spacing.dart
- library/CHANGELOG.md
- library/lib/guidelines/spacings.dart
> 252 bug guideline spacing value

- app/CHANGELOG.md
- app/lib/l10n/ods_flutter_en.arb
> 251 bug guideline spacing

- app/CHANGELOG.md
- docs/components/floatingActionButtons.md
- library/CHANGELOG.md
- library/lib/components/lists/ods_list_standard_item.dart
> 264 bug ods component lists standard lists

- app/CHANGELOG.md
- library/CHANGELOG.md
- library/lib/components/dialogs/ods_alert_dialog.dart
- library/lib/theme/ods_theme.dart
> 247 bug button padding update

- library/lib/guidelines/spacings.dart
> app : spacingNone with a value of 0 px

- app/pubspec.yaml
- docs/components/progressIndicator.md
> Fix doc progress indicator

- app/CHANGELOG.md
- app/lib/ui/components/cards/card_customization.dart
- app/lib/ui/components/cards/card_horizontal.dart
- app/pubspec.yaml
- library/pubspec.yaml
> 271 bug ods   components   cards   horizontal card   divider

- app/CHANGELOG.md
- app/lib/l10n/ods_flutter_en.arb
- app/lib/ui/about/about_screen.dart
- app/lib/ui/components/components_screen.dart
- app/lib/ui/components/detail_screen.dart
- app/lib/ui/guidelines/colours/guideline_colours_screen.dart
- app/lib/ui/guidelines/spacings/guideline_spacings_screen.dart
- app/lib/ui/guidelines/typography/guideline_typography_screen.dart
- app/lib/ui/utilities/component_count_row.dart
- library/CHANGELOG.md
- library/lib/components/card/ods_horizontal_card.dart
- library/lib/components/card/ods_small_card.dart
- library/lib/components/card/ods_vertical_image_first_card.dart
- library/lib/components/lists/ods_list_selection_item.dart
- library/lib/components/lists/ods_list_standard_item.dart
- library/lib/components/lists/ods_list_switch.dart
- library/lib/theme/ods_theme.dart
- library/lib/theme/ods_typography.dart
> 293 typography flutter ios

- docs/_data/data_menus.yml
- docs/_includes/tarteaucitron.html
- docs/_layouts/main.html
- docs/about/Cookies.md
- docs/about/Cookies_docs.md
* Added the cookies management using [TarteAuCitron](https://tarteaucitron.io/fr/)
* Added the custom scripts and custom CSS
* Added a page in the doc to handle the cookies once the first interaction is made.
* Generated the hash using https://www.srihash.org/
> Docs: Add google tag manager

- app/CHANGELOG.md
- app/lib/ui/components/checkboxes/checkboxes.dart
- app/lib/ui/components/radio_buttons/radio_buttons.dart
- app/lib/ui/components/switches/switches.dart
> 295 update components to show label content examples

- app/CHANGELOG.md
- app/lib/ui/components/textfields/textfield.dart
- library/CHANGELOG.md
- library/lib/components/textfield/ods_text_field.dart
> 314 bug text field trailing element text issue

- app/CHANGELOG.md
- app/lib/l10n/ods_flutter_en.arb
- app/lib/ui/components/cards/card_customization.dart
- app/lib/ui/components/cards/card_vertical_header_first.dart
- app/lib/ui/components/cards/card_vertical_image_first.dart
- app/lib/ui/components/components.dart
- library/CHANGELOG.md
- library/lib/components/card/ods_cards_common.dart
- library/lib/components/card/ods_horizontal_card.dart
- library/lib/components/card/ods_small_card.dart
- library/lib/components/card/ods_vertical_header_first_card.dart
- library/lib/components/card/ods_vertical_image_first_card.dart
> 9 ods component cards title first card

- app/CHANGELOG.md
- app/lib/l10n/ods_flutter_en.arb
- app/lib/ui/components/components.dart
- library/CHANGELOG.md
> 334 bug icons button name

- app/CHANGELOG.md
- app/lib/l10n/ods_flutter_en.arb
- app/lib/ui/components/navigation_rail/navigation_rail_enum.dart
- library/CHANGELOG.md
> 333 bug navigation rail name customization

- app/CHANGELOG.md
- app/lib/ui/components/cards/card_customization.dart
- app/lib/ui/components/cards/card_horizontal.dart
- app/lib/ui/components/cards/card_vertical_header_first.dart
- app/lib/ui/components/cards/card_vertical_image_first.dart
- library/CHANGELOG.md
- library/lib/components/card/ods_horizontal_card.dart
- library/lib/components/card/ods_vertical_header_first_card.dart
- library/lib/components/card/ods_vertical_image_first_card.dart
> 329 bug card buttons

- app/CHANGELOG.md
- library/CHANGELOG.md
- library/lib/components/app_bar/top/ods_large_top_app_bar.dart
> 343 bug accessibility add a header to the large title

- app/CHANGELOG.md
- app/lib/l10n/ods_flutter_en.arb
- app/lib/ui/components/buttons/segmented/segmented_button.dart
- app/lib/ui/components/cards/card_horizontal.dart
- app/lib/ui/components/floating_action_button/floating_action_button.dart
- app/lib/ui/components/textfields/textfield.dart
- app/lib/ui/components/textfields/textfield_password.dart
- app/lib/ui/utilities/component_count_row.dart
- library/CHANGELOG.md
- library/lib/components/app_bar/top/ods_large_top_app_bar.dart
> fix name button icons

- app/CHANGELOG.md
- app/lib/ui/components/components_screen.dart
- app/pubspec.lock
- app/pubspec.yaml
- library/CHANGELOG.md
> app : fix bug spacing small card

- app/CHANGELOG.md
- library/CHANGELOG.md
- library/lib/components/snackbars/ods_snackbar.dart
> library and demo : fix bug positionning

- app/CHANGELOG.md
- app/assets/ic_about_terms_of_service.md
- library/CHANGELOG.md
> 356 bug about store reference

- app/lib/ui/components/buttons/buttons_icon/button_icon.dart
- app/lib/ui/components/cards/card_horizontal.dart
- app/lib/ui/components/cards/card_small.dart
- app/lib/ui/components/cards/card_vertical_header_first.dart
- app/lib/ui/components/cards/card_vertical_image_first.dart
- app/lib/ui/components/menus/menu_dropdown.dart
- app/lib/ui/components/menus/menu_exposed_dropdown.dart
- app/lib/ui/components/radio_buttons/radio_buttons.dart
- app/lib/ui/components/textfields/textfield.dart
- library/lib/components/card/ods_horizontal_card.dart
- library/lib/components/card/ods_small_card.dart
- library/lib/components/card/ods_vertical_header_first_card.dart
- library/lib/components/card/ods_vertical_image_first_card.dart
- library/lib/components/chips/ods_action_chips.dart
- library/lib/components/chips/ods_choice_chips.dart
- library/lib/components/chips/ods_filter_chips.dart
- library/lib/components/chips/ods_input_chips.dart
- library/lib/components/lists/ods_list_radio_button.dart
- library/lib/components/menu/item/ods_dropdown_menu_Item.dart
- library/lib/components/menu/ods_dropdown_menu.dart
- library/lib/components/menu/ods_exposed_dropdown_menu.dart
- library/lib/components/textfield/ods_text_field.dart
- library/lib/components/textfield/password/ods_password_text_field.dart
- library/lib/l10n/ods_flutter_en.arb
> 362 ods component accessibility

- app/CHANGELOG.md
- app/lib/ui/components/cards/card_vertical_header_first.dart
- library/CHANGELOG.md
- library/lib/components/card/ods_cards_common.dart
> 340 bug card leading icon

- library/lib/l10n/gen/ods_localizations.dart
- library/lib/l10n/gen/ods_localizations_en.dart
> library : add generated localization file

- .github/actions/setup/action.yml
- app/lib/ui/about/detail/about_file_screen.dart
- app/pubspec.lock
- app/pubspec.yaml
- library/pubspec.yaml
- pubspec.lock
- pubspec.yaml
> updated from intl to 0.19.0

- .github/workflows/jekyll-gh-pages.yml
- docs/Gemfile
- docs/Gemfile.lock
- docs/netlify.toml
> Update the dependencies for Netlify
